export default {
  LISTING_NOT_FOUND: "LISTING_NOT_FOUND",

  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",

  MEMORY_NOT_FOUND: "MEMORY_NOT_FOUND",

  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",

  FAVORITE_NOT_FOUND: "FAVORITE_NOT_FOUND",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  INTERNAL_ERROR: "INTERNAL_ERROR",
};
